name: Deploy to Azure App Service

on:
  push: 
    branches: 
      - main

jobs: 
  build-dockerfile-and-deploy-image-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sabyadocke/testrepo.123:latest